
package vista;


import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JOptionPane;
import modelo.LoginDAO;
import modelo.LoginModelo;

public class Registro extends javax.swing.JFrame {

    LoginModelo lg = new LoginModelo();
    LoginDAO login = new LoginDAO();

    public Registro() {
    initComponents();
    setResizable(false);
    setLocationRelativeTo(null);
     
}
    
    public void validar(){
        String nombre = txtNombreRegistro.getText();
        String apellido = txtApellidoRegistro.getText();
        String telefono = txtTelefonoRegistro.getText();
        String usuario = txtUsuarioRegistro.getText();
        String password = String.valueOf(txtPasswordRegistro.getPassword());
        if (!"".equals(usuario) || !"".equals(password) || !"".equals(nombre) || !"".equals(apellido) || !"".equals(telefono)) {
            lg.setNombre(nombre);
            lg.setApellido(apellido);
            lg.setTelefono(telefono);
            lg.setNombre_usuario(usuario);
            lg.setPassword(password);
            login.Registrar(lg);
            JOptionPane.showMessageDialog(null, "Usuario creado correctamente.");
            Login loginVista = new Login();
            loginVista.setVisible(true);
            dispose();

        }else{
            JOptionPane.showMessageDialog(null, "Ningún campo puede estar vacio.");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cuadro = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelContraseña = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        btnRegistrarse = new javax.swing.JButton();
        txtUsuarioRegistro = new javax.swing.JTextField();
        txtPasswordRegistro = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        labelUsuario1 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        labelUsuario2 = new javax.swing.JLabel();
        txtNombreRegistro = new javax.swing.JTextField();
        txtTelefonoRegistro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnIngresaRegistro = new javax.swing.JButton();
        labelUsuario3 = new javax.swing.JLabel();
        txtApellidoRegistro = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        labelNombreNegocio = new javax.swing.JLabel();
        labelIconoUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cuadro.setBackground(new java.awt.Color(255, 255, 255));

        labelUsuario.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelUsuario.setForeground(new java.awt.Color(0, 0, 0));
        labelUsuario.setText("Usuario:");

        labelContraseña.setBackground(new java.awt.Color(255, 255, 255));
        labelContraseña.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelContraseña.setForeground(new java.awt.Color(0, 0, 0));
        labelContraseña.setText("Contraseña:");

        btnRegistrarse.setBackground(new java.awt.Color(51, 102, 255));
        btnRegistrarse.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });
        btnRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarseActionPerformed(evt);
            }
        });

        txtUsuarioRegistro.setBackground(new java.awt.Color(255, 255, 255));
        txtUsuarioRegistro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtUsuarioRegistro.setForeground(new java.awt.Color(0, 0, 0));
        txtUsuarioRegistro.setBorder(null);

        txtPasswordRegistro.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordRegistro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtPasswordRegistro.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswordRegistro.setBorder(null);

        labelUsuario1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelUsuario1.setForeground(new java.awt.Color(0, 0, 0));
        labelUsuario1.setText("Telefono:");

        labelUsuario2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelUsuario2.setForeground(new java.awt.Color(0, 0, 0));
        labelUsuario2.setText("Nombre:");

        txtNombreRegistro.setBackground(new java.awt.Color(255, 255, 255));
        txtNombreRegistro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtNombreRegistro.setForeground(new java.awt.Color(0, 0, 0));
        txtNombreRegistro.setBorder(null);

        txtTelefonoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        txtTelefonoRegistro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtTelefonoRegistro.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoRegistro.setBorder(null);

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Ya tenes una cuenta?");

        btnIngresaRegistro.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresaRegistro.setForeground(new java.awt.Color(0, 0, 255));
        btnIngresaRegistro.setText("Ingresá");
        btnIngresaRegistro.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnIngresaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresaRegistroActionPerformed(evt);
            }
        });

        labelUsuario3.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelUsuario3.setForeground(new java.awt.Color(0, 0, 0));
        labelUsuario3.setText("Apellido:");

        txtApellidoRegistro.setBackground(new java.awt.Color(255, 255, 255));
        txtApellidoRegistro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtApellidoRegistro.setForeground(new java.awt.Color(0, 0, 0));
        txtApellidoRegistro.setBorder(null);

        javax.swing.GroupLayout cuadroLayout = new javax.swing.GroupLayout(cuadro);
        cuadro.setLayout(cuadroLayout);
        cuadroLayout.setHorizontalGroup(
            cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroLayout.createSequentialGroup()
                .addGroup(cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuadroLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIngresaRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cuadroLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(cuadroLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cuadroLayout.createSequentialGroup()
                        .addGroup(cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelContraseña)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(53, Short.MAX_VALUE))
                    .addGroup(cuadroLayout.createSequentialGroup()
                        .addGroup(cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreRegistro)
                            .addComponent(txtTelefonoRegistro)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoRegistro))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        cuadroLayout.setVerticalGroup(
            cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(labelUsuario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombreRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelUsuario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellidoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUsuario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTelefonoRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelContraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPasswordRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnIngresaRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(cuadro, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 450, 580));

        labelNombreNegocio.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelNombreNegocio.setForeground(new java.awt.Color(255, 255, 255));
        labelNombreNegocio.setText("Formulario de Registro");
        jPanel1.add(labelNombreNegocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        labelIconoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jPanel1.add(labelIconoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarseActionPerformed
//        validar();
    }//GEN-LAST:event_btnRegistrarseActionPerformed

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
//        javax.swing.JOptionPane.showMessageDialog(this, "Intento de login con los datos:\nUsuario: " + txtCorreo.getText() + "\nContraseña: " + String.valueOf(txtPassword.getPassword()), "LOGIN", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        validar();
    }//GEN-LAST:event_btnRegistrarseMouseClicked

    private void btnIngresaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresaRegistroActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIngresaRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresaRegistro;
    private javax.swing.JButton btnRegistrarse;
    private javax.swing.JPanel cuadro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelIconoUsuario;
    private javax.swing.JLabel labelNombreNegocio;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelUsuario1;
    private javax.swing.JLabel labelUsuario2;
    private javax.swing.JLabel labelUsuario3;
    private javax.swing.JTextField txtApellidoRegistro;
    private javax.swing.JTextField txtNombreRegistro;
    private javax.swing.JPasswordField txtPasswordRegistro;
    private javax.swing.JTextField txtTelefonoRegistro;
    private javax.swing.JTextField txtUsuarioRegistro;
    // End of variables declaration//GEN-END:variables
}
